services:
  web:
    container_name: rollenreich
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=http://127.0.0.1:3000
    network_mode: bridge
    restart: unless-stopped
    # Add health check
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:3000/api/auth/providers-status"]
      interval: 30s
      timeout: 10s
      retries: 3
