import { NextResponse } from "next/server";
import { prisma } from "@/prisma";

export async function GET() {
  try {
    const demoProducts = [
      {
        name: "Eco-Friendly Water Bottle",
        description:
          "Sustainable stainless steel water bottle with double-wall insulation",
        price: 24.99,
        sku: "WB-ECO-001",
        color: "Silver",
        material: "Stainless Steel",
        sustainable: true,
        inStock: 50,
        isFeatured: true,
      },
      {
        name: "Organic Cotton T-Shirt",
        description: "Soft organic cotton t-shirt with minimalist design",
        price: 29.99,
        sku: "TS-ORG-002",
        color: "White",
        material: "Organic Cotton",
        sustainable: true,
        inStock: 25,
        isFeatured: false,
      },
      {
        name: "Bamboo Phone Case",
        description: "Protective phone case made from sustainable bamboo",
        price: 19.99,
        sku: "PC-BAM-003",
        color: "Natural",
        material: "Bamboo",
        sustainable: true,
        inStock: 75,
        isFeatured: true,
      },
      {
        name: "Recycled Plastic Backpack",
        description: "Durable backpack made from recycled ocean plastic",
        price: 89.99,
        sku: "BP-REC-004",
        color: "Navy Blue",
        material: "Recycled Plastic",
        sustainable: true,
        inStock: 15,
        isFeatured: false,
      },
      {
        name: "Hemp Notebook",
        description: "Handcrafted notebook with hemp paper and cork cover",
        price: 15.99,
        sku: "NB-HMP-005",
        color: "Brown",
        material: "Hemp/Cork",
        sustainable: true,
        inStock: 40,
        isFeatured: false,
      },
      {
        name: "Solar Power Bank",
        description: "Portable solar-powered charging device",
        price: 45.99,
        sku: "PB-SOL-006",
        color: "Black",
        material: "Recycled Aluminum",
        sustainable: true,
        inStock: 20,
        isFeatured: true,
      },
      {
        name: "Biodegradable Phone Stand",
        description: "Adjustable phone stand made from biodegradable materials",
        price: 12.99,
        sku: "PS-BIO-007",
        color: "Green",
        material: "Biodegradable Plastic",
        sustainable: true,
        inStock: 60,
        isFeatured: false,
      },
      {
        name: "Upcycled Denim Tote Bag",
        description: "Stylish tote bag made from upcycled denim",
        price: 34.99,
        sku: "TB-DEN-008",
        color: "Blue",
        material: "Upcycled Denim",
        sustainable: true,
        inStock: 30,
        isFeatured: false,
      },
      {
        name: "Cork Yoga Mat",
        description:
          "Natural cork yoga mat with excellent grip and sustainability",
        price: 79.99,
        sku: "YM-CRK-009",
        color: "Natural Cork",
        material: "Cork",
        sustainable: true,
        inStock: 18,
        isFeatured: true,
      },
      {
        name: "Recycled Glass Tumbler",
        description: "Beautiful tumbler made from recycled glass",
        price: 16.99,
        sku: "TM-GLR-010",
        color: "Clear",
        material: "Recycled Glass",
        sustainable: true,
        inStock: 45,
        isFeatured: false,
      },
      {
        name: "Organic Wool Sweater",
        description: "Cozy sweater made from ethically sourced organic wool",
        price: 89.99,
        sku: "SW-WOL-011",
        color: "Cream",
        material: "Organic Wool",
        sustainable: true,
        inStock: 12,
        isFeatured: true,
      },
      {
        name: "Bamboo Cutting Board",
        description:
          "Durable bamboo cutting board with antimicrobial properties",
        price: 32.99,
        sku: "CB-BAM-012",
        color: "Natural",
        material: "Bamboo",
        sustainable: true,
        inStock: 35,
        isFeatured: false,
      },
      {
        name: "Recycled Aluminum Laptop Stand",
        description: "Adjustable laptop stand made from recycled aluminum",
        price: 54.99,
        sku: "LS-ALU-013",
        color: "Silver",
        material: "Recycled Aluminum",
        sustainable: true,
        inStock: 22,
        isFeatured: false,
      },
      {
        name: "Organic Cotton Bed Sheets",
        description: "Luxurious bed sheets made from certified organic cotton",
        price: 129.99,
        sku: "BS-COT-014",
        color: "White",
        material: "Organic Cotton",
        sustainable: true,
        inStock: 8,
        isFeatured: true,
      },
      {
        name: "Recycled Paper Planner",
        description: "Weekly planner made from 100% recycled paper",
        price: 22.99,
        sku: "PL-PAP-015",
        color: "Kraft",
        material: "Recycled Paper",
        sustainable: true,
        inStock: 55,
        isFeatured: false,
      },
      {
        name: "Sustainable Wooden Watch",
        description: "Elegant watch crafted from sustainably sourced wood",
        price: 149.99,
        sku: "WA-WOD-016",
        color: "Walnut",
        material: "Sustainable Wood",
        sustainable: true,
        inStock: 10,
        isFeatured: true,
      },
      {
        name: "Recycled Plastic Desk Organizer",
        description: "Modular desk organizer made from ocean plastic waste",
        price: 38.99,
        sku: "DO-PLA-017",
        color: "Gray",
        material: "Recycled Plastic",
        sustainable: true,
        inStock: 28,
        isFeatured: false,
      },
      {
        name: "Organic Linen Curtains",
        description: "Natural linen curtains with a minimalist design",
        price: 94.99,
        sku: "CU-LIN-018",
        color: "Beige",
        material: "Organic Linen",
        sustainable: true,
        inStock: 15,
        isFeatured: false,
      },
      {
        name: "Bamboo Fiber Dinnerware Set",
        description: "Complete dinnerware set made from bamboo fiber",
        price: 67.99,
        sku: "DW-BAM-019",
        color: "Natural",
        material: "Bamboo Fiber",
        sustainable: true,
        inStock: 20,
        isFeatured: true,
      },
      {
        name: "Recycled Steel Water Bottle",
        description:
          "Insulated water bottle made from recycled stainless steel",
        price: 28.99,
        sku: "WB-STL-020",
        color: "Matte Black",
        material: "Recycled Steel",
        sustainable: true,
        inStock: 42,
        isFeatured: false,
      },
    ];

    const result = await prisma.product.createMany({
      data: demoProducts,
      skipDuplicates: true,
    });

    return NextResponse.json({
      success: true,
      message: `Successfully created ${result.count} demo products`,
      count: result.count,
    });
  } catch (error) {
    console.error("Error creating demo products:", error);
    return NextResponse.json(
      {
        success: false,
        message: "Failed to create demo products",
        error: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}
